title: Istark Cybersecurity Lab
description: Research notes and analysis on cybersecurity topics
baseurl: ""
url: "https://istaarkk.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Permalinks
permalink: /:categories/:year/:month/:day/:title:output_ext

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - README.md
  - CNAME
  - config.yaml
  - static/
  
# Collections
collections:
  posts:
    output: true
    
# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
